#HAPPY PATH: retrieveIdPublicServiceList  - 200 # status code
openapi: 3.0.0
info:
  title: recupero della lista degli PublicService 
  description: L’utente di backend invoca in GET il metodo retrieveIdPublicServiceList passando in input il parametro identificatore del tipo di PublicService da recuperare
  version: 1.0.2
servers:
  - url: http://<url_service_catalog>
    description: Local server
  - url: http://<url_service_catalog>
    description: Development server
  - url: http://<url_service_catalog>
    description: Test server
  - url: http://<url_service_catalog>
    description: Certification server
  - url: http://<url_service_catalog>
    description: Production server
paths:
  /api/v1/data-service/list/:
    get:
      security:
        - Authorization: []         
      tags:
        - retrieveIdPublicServiceList 
      summary: restituisce la lista delle PublicService  
      description: il metodo get restituisce la lista delle PublicService 
      parameters:
        - in: query
          name: name
          required: false
          schema:
            type: string
          description: Nome del procedimento amministrativo 
        - in: query
          name: publicOrganizationId
          required: true
          schema:
            type: string
          description: Identificativo dell’ente del procedimento amministrativo
       
      responses:
        '200':    # status code
          description: Successful operation
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/publicServiceResponse'

components:
  schemas:  

    publicServiceResponse:
      type: object
      required:
        - code
        - description
        - publicService
      properties:
        code:
          type: string
          description: Rif response code
        description:
          type: string
          description: Eventuale descrizione dell’errore
        message:
          type: string
          description: Eventuale messaggio di errore
        publicService:
          $ref: '#/components/schemas/publicService'

    publicService:
      type: object
      description: Array di oggetti JSON
      required:
        - name
        - description
        - policyCode
      properties:
        id:
          type: integer
          description: identificativo del procedimento amministrativo
        name:
          type: string
          description: Nome del procedimento amministrativo  
        description:
          type: string
          description: Descrizione del procedimento amministrativo
        policyCode:
          $ref: '#/components/schemas/policyCode'

    policyCode:
      type: object
      description: Identificativo univoco definito dall’Comunità Europea
      required:
        - id
        - keyId
        - value
      properties:
        id:
          type: integer
          description: Identificatore della tabella type chiave esterna 
        keyId:
          type: integer
          description: Attributo keyId della tabella Type con filtro code=”policy_code”
        value:
          type: string
          description: Attributo value della tabella Type con filtro code=”policy_code”    
          
          
  securitySchemes:
    Authorization:            # Bearer <Voucher PDND>
      type: http
      scheme: bearer
      bearerFormat: JWT       
    