#HAPPY PATH: retrievEevidenceTypeList - 200 # status code
openapi: 3.0.0
info:
  title: lista delle Tipologie di prova per specifico requisito
  description: Estrae la lista di Tipologia di prova aderente all'output di retrieveRequirementList
  version: 1.0.5
servers:
  - url: http://<url_service_catalog>
    description: Local server
  - url: http://<url_service_catalog>
    description: Development server
  - url: http://<url_service_catalog>
    description: Test server
  - url: http://<url_service_catalog>
    description: Certification server
  - url: http://<url_service_catalog>
    description: Production server
paths:
  /api/v1/evidence-type/list:
    get:
      security:
        - Authorization: []         
      tags:
        - retrieveEvidenceTypeList
      summary: restituisce la lista delle Tipologie di prova per specifico requisito non necessariamente italiane. 
      description: La lista delle prove delle tipologie ristrette all'output di retrieveRequirementList. 
      parameters:
        - in: query
          name: queryId
          required: true
          schema:
            type: string
          description: Questo parametro deve essere valorizzato con la seguente stringa "urn:oots:eb:ebxml-regrep:queries:evidencetypes-by-requirement-and-jurisdiction".
        - in: query
          name: requirement-id
          required: true
          schema:
            type: string
          description: identificativo per requisito per i quali si richiedono le Tipologie di prova.
        - in: query
          name: country-code
          required: false
          schema:
            type: string
          description: Il codice del paese per i quali sono mappate le Tipologie di prova.
        - in: query
          name: jurisdiction-admin-l2
          required: false
          schema:
            type: string
          description: codice di secondo livello per l'amministrazione per la giurisdizione della tipologia di prova. Il codice è NUTS. Il codice deve essere combinato con il countrycode
        - in: query
          name: jurisdiction-admin-l3
          required: false
          schema:
            type: string
          description: codice di terzo livello per l'amministrazione per la giurisdizione della tipologia di prova. Il codice è LAU. Il codice deve essere combinato con il countrycode
      responses:
        '200':    # status code
          description: Successful operation
          content:
            application/xml:
              schema:
                  $ref: '#/components/schemas/QueryResponse'
components:
  schemas:     
    QueryResponse:
      type: object
      xml:
        prefix: 'query'
        namespace: urn:oasis:names:tc:ebxml-regrep:xsd:query:4.0
      properties:
        xmlns:
          type: string
          default: urn:oasis:names:tc:ebxml-regrep:xsd:lcm:4.0
          xml:
            attribute: true
        xmlns:lcm:
          type: string
          default: urn:oasis:names:tc:ebxml-regrep:xsd:lcm:4.0
          xml:
            attribute: true
        xmlns:rim:
          type: string
          default: urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0
          xml:
            attribute: true
        xmlns:rs:
          type: string
          default: urn:oasis:names:tc:ebxml-regrep:xsd:rs:4.0
          xml:
            attribute: true    
        xmlns:xsi:
          type: string
          default: http://www.w3.org/2001/XMLSchema-instance
          xml:
            attribute: true      
        xsi:schemaLocation:
          type: string
          default: urn:oasis:names:tc:ebxml-regrep:xsd:lcm:4.0
          xml:
            attribute: true  
        requestId:
          type: string
          example: c4369c4d-740e-4b64-80f0-7b209a66d629
          xml:
            attribute: true   
        status:
          type: string
          default: urn:oasis:names:tc:ebxmlregrep:ResponseStatusType:Success
          xml:
            attribute: true             
        RegistryObjectList:
          type: object
          xml:
            prefix: 'rim'
          properties:
            RegistryObject:
              type: object
              xml:
                prefix: 'rim'
              required:
                - id
              properties:
                id:
                  type: string
                  xml:
                    attribute: true    
                Requirement:
                  type: object 
                  required:
                    - Identifier
                  properties:
                    xmlns:
                      type: string
                      default: http://data.europa.eu/sdg#
                      xml:
                        attribute: true
                    xmlns:xsi:
                      type: string
                      default: http://www.w3.org/2001/XMLSchema-instance
                      xml:
                        attribute: true  
                    Identifier:    
                      type: string
                    Name:
                      type: string
                    ReferenceFramework:
                      $ref: '#/components/schemas/ReferenceFramework'
                    IssuedBy:
                      $ref: '#/components/schemas/IssuedBy'   
                    EvidenceTypeList:
                      $ref: '#/components/schemas/EvidenceTypeList'
                      
    ReferenceFramework:
      type: object
      required:
        - Identifier
        - Jurisdiction
      properties:
        Identifier:
          type: string
        Title:
          type: string
        Description:
          type: string
        RelatedTo: 
          type: object 
          properties:
            Identifier:
              type: string
        Jurisdiction: 
          type: object 
          required:
           - AdminUnitLevel1
          properties:
            AdminUnitLevel1:
              type: string   
              
    IssuedBy:
      type: object
      properties:
        Identifier:
          type: string
        Name:
          type: string
        Classification:
          type: integer
          
          
    EvidenceTypeList:
      type: object
      required:
        - Identifier
        - EvidenceType
      properties:
        Identifier:
          type: string
        Name:
          type: string  
        Description:
          type: string            
        EvidenceType:
          type: object
          required:
            - EvidenceTypeClassification
          properties:
            Identifier:
              type: string
            Description:
              type: string
            EvidenceTypeClassification:
              type: string
            Jurisdiction:
              type: object
              properties: 
                AdminUnitLevel1:
                  type: string
                AdminUnitLevel2:
                  type: string                  
                AdminUnitLevel3:
                  type: string              
          
  securitySchemes:
    Authorization:            # Bearer <Voucher PDND>
      type: http
      scheme: bearer
      bearerFormat: JWT                   