x-commons:
  ratelimit-headers: &ratelimit-headers
    X-RateLimit-Limit:
      $ref: '#/components/headers/X-RateLimit-Limit'
    X-RateLimit-Remaining:
      $ref: '#/components/headers/X-RateLimit-Remaining'
    X-RateLimit-Reset:
        $ref: '#/components/headers/X-RateLimit-Reset'
  common-responses: &common-responses
    '400':
      $ref: '#/components/responses/400BadRequest'
    '401':
      $ref: '#/components/responses/401Unauthorized'
    '429':
      $ref: '#/components/responses/429TooManyRequests'
    '503':
      $ref: '#/components/responses/503ServiceUnavailable'
    default:
      $ref: '#/components/responses/default'


openapi: 3.0.1
info:
  title: Web Services for Agid
  description: >
    ### Documentazione

    Il servizio effettua nel solo ambito del Progetto Single Digital Gateway e 
    in particolare delle Procedure Nazionali che richiedono il suo utilizzo ,
    la verifica di esistenza e validità del codice fiscale di una persona fisica
    e della corrispondenza di questo con i dati anagrafici indicati in input per il soggetto
    in base a quanto presente nell’Archivio Anagrafico del Sistema dell’AE

  termsOfService: 'Terms:'
  contact:
    name: Developers
    url: www.site.com
    email: p.aiello@accenture.com
  license:
    name: Licence
    url: www.site.com
  version: API VERSION 1
servers:
  - url: http://localhost:8080
    description: Inferred Url
x-summary: >
    ### Documentazione

    Il servizio effettua nel solo ambito del Progetto Single Digital Gateway e 
    in particolare delle Procedure Nazionali che richiedono il suo utilizzo ,
    la verifica di esistenza e validità del codice fiscale di una persona fisica
    e della corrispondenza di questo con i dati anagrafici indicati in input per il soggetto
    in base a quanto presente nell’Archivio Anagrafico del Sistema dell’AE

paths:
   /verifica/pf:
    post:
      tags:
        - Verifica persona fisica
      summary: Effettua la verifica della persona fisica
      description: >-
        La chiamata permette tramite l'inserimento del codice fiscale e dei dati
        anagrafici della persona fisica di verificarne la corrispondenza con i
        dati presenti nell'archivio anagrafico
      operationId: verificaPf
      requestBody:
        description: >-
          Parametri relativi al codice fiscale e i dati anagrafici della persona
          fisica da verificare 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputPfDto'
            examples:
              Esempio di verifica persona fisica tramite il codice fiscale e i dati anagrafici:
                summary: Verifica PF
                description: >-
                  Esempio di verifica persona fisica tramite il codice fiscale e
                  i dati anagrafici
                value:
                  codiceFiscale: TLEMRA83A01H501T
                  cognome: TELEM
                  nome: MARIO
                  sesso: M
                  dataNascita: '1983-01-01'
                  comuneNascita: ROMA
                  provNascita: RM
                  statoNascita: ''
        required: true
      responses:
        '200':
          description: >-
            Ritorno positivo della chiamata, restituisce un valore TRUE/FALSE
            che identifica se la persona fisica è valida, inoltre ai fini della consistenza delle API
            restituisce i dati di input utilizzati per la verifica.
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OutputVerificaPfDto'
        '400':
          description: >-
            Il servizio non è in grado di elaborare la richiesta in quanto è
            possibile che i dati di input non siano corretti o le verifiche sul
            flusso hanno prodotto degli errori.
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ServiceErrorDto'
        '401':
          description: >-
            Il client non è autorizzato ad effettuare la chiamata, verificare il
            Voucher PDND, il client_id ed il certificato fornito.
          content:
            application/problem+json: {}                          
        '403':
          description: >-
            Il client non è autorizzato ad effettuare la chiamata, verificare il
            Voucher PDND, il client_id ed il certificato fornito.
          content:
            application/problem+json: {}
        '404':
          description: Servizio non trovato, verificare che l'url sia corretta.
          content:
            application/problem+json: {}
        '429':
          description: Raggiunto il limite di richieste
          headers:
            Retry-After:
              $ref: '#/components/headers/Retry-After'
            X-RateLimit-Limit:
              $ref: '#/components/headers/X-RateLimit-Limit'
            X-RateLimit-Remaining:
              $ref: '#/components/headers/X-RateLimit-Remaining'
            X-RateLimit-Reset:
              $ref: '#/components/headers/X-RateLimit-Reset'
        '503':
          description: Errore interno del sistema per possibile malfunzionamento.
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ServiceErrorDto'
        default:
          description: default response
          content:
            application/problem+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InputPfDto'

security:
     - bearerAuth: []
components:
  schemas:
  
    Problem:
      properties:
        detail:
          description: |
            A human readable explanation specific to this occurrence of the
            problem. You MUST NOT expose internal informations, personal
            data or implementation details through this field.
          example: Request took too long to complete.
          type: string
        instance:
          description: |
            An absolute URI that identifies the specific occurrence of the problem.
            It may or may not yield further information if dereferenced.
          format: uri
          type: string
        status:
          description: |
            The HTTP status code generated by the origin server for this occurrence
            of the problem.
          example: 503
          exclusiveMaximum: true
          format: int32
          maximum: 600
          minimum: 100
          type: integer
        title:
          description: |
            A short, summary of the problem type. Written in english and readable
            for engineers (usually not suited for non technical stakeholders and
            not localized); example: Service Unavailable
          type: string
        type:
          default: about:blank
          description: |
            An absolute URI that identifies the problem type.  When dereferenced,
            it SHOULD provide human-readable documentation for the problem type
            (e.g., using HTML).
          format: uri
          type: string
      type: object      

    ServiceErrorDto:
      type: object
      properties:
        status:
          type: integer
          format: int32
        messaggi:
          type: array
          items:
            type: string
      description: Oggetto di ritorno per la gestione degli errori
    InputPfDto:
      required:
        - codiceFiscale
        - cognome
        - comuneNascita
        - dataNascita
        - nome
        - provNascita
        - sesso
        - statoNascita
      type: object
      properties:
        codiceFiscale:
          type: string
        cognome:
          type: string
        nome:
          type: string
        sesso:
          type: string
          enum:
            - M
            - F
        dataNascita:
          type: string
          example: '2022-01-01'
        comuneNascita:
          type: string
          example: ROMA
        provNascita:
          maxLength: 2
          minLength: 2
          type: string
          description: Sono consentite le sigle ufficiali delle province italiane. Da non valorizzare in caso di nato in ex Comune Italiano
          example: RM
        statoNascita:
          type: string
          description: >-
            Lo stato è da inserire quando la persona fisica non è nata in
            italia. In caso contrario inviare stringa vuota.
          example: SVIZZERA
    OutputVerificaPfDto:
      type: object
      properties:
        dati:
          $ref: '#/components/schemas/InputPfDto'
        valido:
          type: boolean
          description: Campo di validità della persona fisica
        messaggio:
          type: string
          description: Messaggio di ritorno del servizio di verifica
          enum:
            - Persona fisica verificata con successo
            - CF formalmente errato
            - CF calcolato sulla base dei dati forniti diverso da quello
              indicato
            - CF non presente in AT
            - CF presente in AT, definitivo, i dati anagrafici non corrispondono
              a quelli indicati
            - CF presente in AT, definitivo, i dati anagrafici corrispondono a
              quelli indicati, soggetto deceduto
            - CF presente in AT, definitivo, i dati anagrafici corrispondono a
              quelli indicati
            - CF presente in AT, definitivo, i dati anagrafici corrispondono a
              quelli indicati, soggetto adottato
            - CF presente in AT, definitivo, i dati anagrafici corrispondono a
              quelli indicati, soggetto espulso
            - CF presente in AT, definitivo, i dati anagrafici corrispondono a
              quelli indicati, attribuito sulla base di documenti falsi
            - CF presente in AT, base di omocodia
            - CF presente in AT, collegato ad altro codice fiscale i dati
              anagrafici di input non coincidono con quelli associati al
              collegato
            - CF presente in AT, collegato ad altro codice fiscale i dati
              anagrafici di input coincidono con i dati anagrafici associati al
              collegato
            - CF presente in AT, collegato ad altro codice fiscale i dati
              anagrafici di input coincidono con i dati anagrafici associati al
              collegato, risulta attribuito in base a documenti falsi
      description: Oggetto generico di ritorno per la verifica del PF
  
  securitySchemes:
    bearerAuth:
      type: http
      description: Voucher PDND
      scheme: bearer
      bearerFormat: JWT
      
  headers:
    Retry-After:
      description: |-
        Retry contacting the endpoint *at least* after seconds.
        See https://tools.ietf.org/html/rfc7231#section-7.1.3
      schema:
        type: string
    WWW-Authenticate:
      description: |-
        Auth realm=APIkey
        See https://tools.ietf.org/html/rfc7235#section-4.1
      schema:
        type: string
    X-RateLimit-Limit:
      description: The number of allowed requests in the current period
      schema:
        type: string
    X-RateLimit-Remaining:
      description: The number of remaining requests in the current period
      schema:
        type: string
    X-RateLimit-Reset:
      description: The number of seconds left in the current period
      schema:
        type: string
  
        
  responses:
    400BadRequest:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
      description: Bad Request
    401Unauthorized:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
      headers:
        WWW-Authenticate:
          $ref: '#/components/headers/WWW-Authenticate'
      description: Not authorized
    403Forbidden:
      description: Forbidden
    404NotFound:
      description: Not Found
    429TooManyRequests:
      description: Too many requests
      headers:
        Retry-After:
          $ref: '#/components/headers/Retry-After'
        X-RateLimit-Limit:
          $ref: '#/components/headers/X-RateLimit-Limit'
        X-RateLimit-Remaining:
          $ref: '#/components/headers/X-RateLimit-Remaining'
        X-RateLimit-Reset:
          $ref: '#/components/headers/X-RateLimit-Reset'
    503ServiceUnavailable:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
      description: Service Unavailable
      headers:
        Retry-After:
          $ref: '#/components/headers/Retry-After'
    default:
      description: Unexpected error    