#UNHAPPY PATH: retrieveEvidenceTypeList - 400 # status code
openapi: 3.0.0
info:
  title: lista delle Tipologie di prova per specifico requisito
  description: Estrae la lista di Tipologia di prova aderente all'output di retrieveRequirementList
  version: 1.0.4
servers:
  - url: http://<url_service_catalog>
    description: Local server
  - url: http://<url_service_catalog>
    description: Development server
  - url: http://<url_service_catalog>
    description: Test server
  - url: http://<url_service_catalog>
    description: Certification server
  - url: http://<url_service_catalog>
    description: Production server
paths:
  /api/v1/evidence-type/list:
    get:
      security:
        - Authorization: []       
      tags:
        - retrieveEvidenceTypeList
      summary: restituisce la lista delle Tipologie di prova per specifico requisito non necessariamente italiane. 
      description: La lista delle prove delle tipologie ristrette all'output di retrieveRequirementList. 
      parameters:
        - in: query
          name: queryId
          required: true
          schema:
            type: string
          description: Questo parametro deve essere valorizzato con la seguente stringa "urn:oots:eb:ebxml-regrep:queries:evidencetypes-by-requirement-and-jurisdiction".
        - in: query
          name: requirement-id
          required: true
          schema:
            type: string
          description: identificativo per requisito per i quali si richiedono le Tipologie di prova.
        - in: query
          name: country-code
          required: false
          schema:
            type: string
          description: Il codice del paese per i quali sono mappate le Tipologie di prova.
        - in: query
          name: jurisdiction-admin-l2
          required: false
          schema:
            type: string
          description: codice di secondo livello per l'amministrazione per la giurisdizione della tipologia di prova. Il codice è NUTS. Il codice deve essere combinato con il countrycode
        - in: query
          name: jurisdiction-admin-l3
          required: false
          schema:
            type: string
          description: codice di terzo livello per l'amministrazione per la giurisdizione della tipologia di prova. Il codice è LAU. Il codice deve essere combinato con il countrycode
      responses:
        '400':    # status code
          description: Bad Request
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/QueryResponse'
components:
  schemas:
    QueryResponse:
      type: object
      xml:
        prefix: 'query'
        namespace: urn:oasis:names:tc:ebxml-regrep:xsd:query:4.0
      properties:
        xmlns:
          type: string
          default: urn:oasis:names:tc:ebxml-regrep:xsd:lcm:4.0
          xml:
            attribute: true
        xmlns:lcm:
          type: string
          default: urn:oasis:names:tc:ebxml-regrep:xsd:lcm:4.0
          xml:
            attribute: true
        xmlns:rim:
          type: string
          default: urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0
          xml:
            attribute: true
        xmlns:rs:
          type: string
          default: urn:oasis:names:tc:ebxml-regrep:xsd:rs:4.0
          xml:
            attribute: true    
        xmlns:xsi:
          type: string
          default: http://www.w3.org/2001/XMLSchema-instance
          xml:
            attribute: true      
        xsi:schemaLocation:
          type: string
          default: urn:oasis:names:tc:ebxml-regrep:xsd:lcm:4.0
          xml:
            attribute: true  
        status:
          type: string
          default: urn:oasis:names:tc:ebxmlregrep:ResponseStatusType:Error
          xml:
            attribute: true
        Exception:
          type: object
          xml:
            prefix: 'rs'
          properties:
            xsi:type:
              type: string
              default: rs:ObjectNotFoundExceptionType
              xml:
                attribute: true
            severity:
              type: string
              default: urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error
              xml:
                attribute: true            
            message:
              type: string
              default: List of requirements requested is empty
              xml:
                attribute: true                 
            code:
              type: string
              default: EB:ERR:0001
              xml:
                attribute: true         
  securitySchemes:
    Authorization:            # Bearer <Voucher PDND>
      type: http
      scheme: bearer
      bearerFormat: JWT