#HAPPY PATH + UNHAPPY PATH : retrieveRequirementList
openapi: 3.0.0
info:
  title: restituisce la lista delle Tipologie di prova per specifico requisito
  description: L’insieme delle Tipologie di prova necessarie a soddisfare ogni specifico Requisito sarà restituito dall’Evidence Broker IT.
  version: 1.0.9
servers:
  - url: http://<url_service_catalog>
    description: Local server
  - url: http://<url_service_catalog>
    description: Development server
  - url: http://<url_service_catalog>
    description: Test server
  - url: http://<url_service_catalog>
    description: Certification server
  - url: http://<url_service_catalog>
    description: Production server
paths:
  /api/v1/requirement/list:
    get:
      security:
        - Authorization: []        
      tags:
        - retrieveRequirementList
      summary: restituisce la lista delle Tipologie di prova per specifico requisito. 
      description: L’insieme delle Tipologie di prova necessarie a soddisfare ogni specifico Requisito sarà restituito dall’Evidence Broker IT. 
      parameters:
        - in: query
          name: queryId
          required: true
          schema:
            type: string
          description: Questo parametro deve essere valorizzato con la seguente stringa "urn:oots:eb:ebxml-regrep:queries:requirementsby-procedure-and-jurisdiction".
        - in: query
          name: proc-identifier
          required: true
          schema:
            type: string
          description: Identificativo della Procedimento amministrativo al livello Europeo al fine di filtrare i Requirement.
        - in: query
          name: proc-jurisdiction
          required: false
          schema:
            type: string
          description: Giurisdizione della Procedure/Procedimento amministrativo al fine di filtrare i Requirement utilizzati nello Stato Membro. La codifica da utilizzare è ISO 3166-2
      responses:
        '200':    # status code
          description: Successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/QueryResponse'
              example:
                xmlns: urn:oasis:names:tc:ebxml-regrep:xsd:lcm:4.0
                xmlns:lcm: urn:oasis:names:tc:ebxml-regrep:xsd:lcm:4.0
                xmlns:rim: urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0
                xmlns:rs: urn:oasis:names:tc:ebxml-regrep:xsd:rs:4.0
                xmlns:xsi: http://www.w3.org/2001/XMLSchema-instance
                xsi:schemaLocation: urn:oasis:names:tc:ebxml-regrep:xsd:lcm:4.0
                requestId: c4369c4d-740e-4b64-80f0-7b209a66d629
                status: urn:oasis:names:tc:ebxmlregrep:ResponseStatusType:Success      
                RegistryObjectList: 
                  RegistryObject:
                    id: 315cfd75-6605-49c4-b0fe-799833b41099
                    Requirement:
                      xmlns: http://data.europa.eu/sdg#
                      xmlns:xsi: http://www.w3.org/2001/XMLSchema-instance
                      Identifier: 315cfd75-6605-49c4-b0fe-799833b41099
                      Name: bachelor's degree
                      
                      
                      ReferenceFramework:
                      
                      - Identifier: 118fd444-6443-42be-a084-c9fbfd1f674d
                        Title: Procedure 5 - Annex II of SDG as Implemented in the Italian   Portal
                        Description: Procedure 5 of Annex II of the Regulation (EU) 2018/1724 the European Parliament an of the Council of October   2 establishing a single digital gateway to providaccess to informati to procedures and to assistance anproblem-solving   services  amending Regulation (EU No 10/2012
                        RelatedTo: 
                          Identifier: http://data.europa.eu/eli/reg/2018/1724/oj#Annex-5
                        Jurisdiction:
                            AdminUnitLevel1: IT                
                
                      - Identifier: 218fd444-6443-42be-a084-c9fbfd1f674d
                        Title: Procedure 5 - Annex II of SDG as Implemented in the Italian   Portal
                        Description: Procedure 5 of Annex II of the Regulation (EU) 2018/1724 the European Parliament and of the Council of October   2 establishing a single digital gateway to providaccess to   informati to procedures and to assistance anproblem-solving   services  amending Regulation (EU) No 10/2012
                        RelatedTo: 
                          Identifier: http://data.europa.eu/eli/reg/2018/1724/oj#Annex-5
                        Jurisdiction:
                          AdminUnitLevel1: IT                           
  
                          
        '400':    # status code
          description: Failure operation
          content:
            application/xml:
              schema:
                  $ref: '#/components/schemas/QueryResponse'
              example:
                xmlns: urn:oasis:names:tc:ebxml-regrep:xsd:lcm:4.0
                xmlns:lcm: urn:oasis:names:tc:ebxml-regrep:xsd:lcm:4.0
                xmlns:rim: urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0
                xmlns:rs: urn:oasis:names:tc:ebxml-regrep:xsd:rs:4.0
                xmlns:xsi: http://www.w3.org/2001/XMLSchema-instance
                xsi:schemaLocation: urn:oasis:names:tc:ebxml-regrep:xsd:lcm:4.0
                requestId: c4369c4d-740e-4b64-80f0-7b209a66d629
                status: urn:oasis:nammes:tc:ebxml-regrep:ResponseStatusType:Failure 
                Exception:
                  xsi:type: rs:ObjectNotFoundExceptionType
                  severity: urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error
                  message: No Evidence Providers were found based on the given parameters
                  code: EB:ERR:0001
                          
components:
  schemas:     
    QueryResponse:
      type: object
      required:
       - requestId
       - status
      xml:
        prefix: 'query'
        namespace: urn:oasis:names:tc:ebxml-regrep:xsd:query:4.0
      properties:
        xmlns:
          type: string
          default: urn:oasis:names:tc:ebxml-regrep:xsd:lcm:4.0
          xml:
            attribute: true
        xmlns:lcm:
          type: string
          default: urn:oasis:names:tc:ebxml-regrep:xsd:lcm:4.0
          xml:
            attribute: true
        xmlns:rim:
          type: string
          default: urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0
          xml:
            attribute: true
        xmlns:rs:
          type: string
          default: urn:oasis:names:tc:ebxml-regrep:xsd:rs:4.0
          xml:
            attribute: true    
        xmlns:xsi:
          type: string
          default: http://www.w3.org/2001/XMLSchema-instance
          xml:
            attribute: true      
        xsi:schemaLocation:
          type: string
          default: urn:oasis:names:tc:ebxml-regrep:xsd:lcm:4.0
          xml:
            attribute: true  
        requestId:
          type: string
          example: c4369c4d-740e-4b64-80f0-7b209a66d629
          xml:
            attribute: true   
        status:
          type: string
          default: urn:oasis:names:tc:ebxmlregrep:ResponseStatusType:Success
          xml:
            attribute: true             
            
        Exception:
          type: object
          xml:
            prefix: 'rs'
          properties:
            xsi:type:
              type: string
              default: rs:ObjectNotFoundExceptionType
              xml:
                attribute: true
            severity:
              type: string
              default: urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error
              xml:
                attribute: true            
            message:
              type: string
              example: List of requirements requested is empty
              xml:
                attribute: true                 
            code:
              type: string
              example: EB:ERR:0001
              xml:
                attribute: true            
            
            
            
        RegistryObjectList:
          type: object
          xml:
            prefix: 'rim'
          properties:
            RegistryObject:
              type: object
              xml:
                prefix: 'rim'
              required:
                - id
              properties:
                id:
                  type: string
                  xml:
                    attribute: true    
                Requirement:
                  type: object 
                  required:
                    - Identifier
                  properties:
                    xmlns:
                      type: string
                      default: http://data.europa.eu/sdg#
                      xml:
                        attribute: true
                    xmlns:xsi:
                      type: string
                      default: http://www.w3.org/2001/XMLSchema-instance
                      xml:
                        attribute: true  
                    Identifier:    
                      type: string
                    Name:
                      type: string
                    ReferenceFramework:  
                      $ref: '#/components/schemas/ReferenceFrameworkArray'
                      
    ReferenceFrameworkArray:
      type: array
      items:
        $ref: '#/components/schemas/ReferenceFramework'
      xml:
        name: ReferenceFramework
        wrapped: false
                  
                  
    ReferenceFramework:
      type: object
      required:
        - Identifier
      properties:
        Identifier:
          type: string
        Title:
          type: string
        Description:
          type: string
        RelatedTo: 
          type: object 
          properties:
            Identifier:
              type: string
        Jurisdiction: 
          type: object 
          required:
           - AdminUnitLevel1
          properties:
            AdminUnitLevel1:
              type: string   



                      
          
  securitySchemes:
    Authorization:            # Bearer <Voucher PDND>
      type: http
      scheme: bearer
      bearerFormat: JWT                   