#HAPPY PATH + UNHAPPY PATH : retrieveIdPublicService
openapi: 3.0.0
info:
  title: recupero della lista degli PublicService 
  description: L’utente di backend invoca in GET il metodo retrieveIdPublicServiceList passando in input il parametro identificatore del tipo di PublicService da recuperare
  version: 1.0.6
servers:
  - url: http://<url_service_catalog>
    description: Local server
  - url: http://<url_service_catalog>
    description: Development server
  - url: http://<url_service_catalog>
    description: Test server
  - url: http://<url_service_catalog>
    description: Certification server
  - url: http://<url_service_catalog>
    description: Production server
paths:
  /api/v1/public-service/list/:
    get:
      security:
        - Authorization: []         
      tags:
        - retrieveIdPublicService 
      summary: restituisce la lista delle PublicService  
      description: il metodo get restituisce la lista delle PublicService 
      parameters:
        - in: query
          name: name
          required: true
          schema:
            type: string
          description: Nome del procedimento amministrativo 
        - in: query
          name: publicOrganizationId
          required: true
          schema:
            type: string
          description: Identificativo dell’ente del procedimento amministrativo
       
      responses:
        '200':    # status code
          description: Successful operation
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/publicServiceResponse'


        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '402':
          $ref: '#/components/responses/402'          
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '429':
          $ref: '#/components/responses/429'
        '500':
          $ref: '#/components/responses/500'


components:

  responses:
    '400':
      description: Bad Request - Could not parse request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errore'
          example:
           - code: '400'
             message: Bad Request
             description: Could not parse request
    '401':
      description: Unauthorized - No authentication credentials provided or authentication failed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errore'
          example:
           - code: '401'
             message: Unauthorized
             description: No authentication credentials provided or authentication failed            
    '402':
      description: No Rows Selected - There is not any row extracted
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errore'
          example:
           - code: '402'
             message: No Rows Selected
             description: There is not any row extracted                 
    '403':
      description: Forbidden - Authenticated user does not have access
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errore'
          example:
           - code: '403'
             message: Forbidden
             description: Forbidden - Authenticated user does not have access                 
    '404':
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errore'
          example:
           - code: '404'
             message: Not Found
             description: File Not Found             
    '429':
      description: Too Many Requests - Request rejected due to rate limiting
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errore'
          example:
           - code: '429'
             message: Too Many Requests
             description: Request rejected due to rate limiting            
    '500':
      description: An internal server error occurred
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errore'
          example:
           - code: '500'
             message: An internal server error occurred
             description: An internal server error occurred


  schemas:  

    publicServiceResponse:
      type: object
      required:
        - code
        - description
        - publicService
      properties:
        code:
          type: string
          description: Rif response code
          example: 200
        description:
          type: string
          description: Eventuale descrizione code
          example: Successful operation
        message:
          type: string
          description: Eventuale messaggio di errore
        publicService:
          $ref: '#/components/schemas/publicService'

    publicService:
      type: object
      description: Array di oggetti JSON
      required:
        - publicServiceId
        - euId
        - name
        - description
        - publicOrganization
      properties:
        publicServiceId:
          type: integer
          description: Identificativo tecnico della tabella del procedimento amministrativo
          example: 101
        euId:
          type: string
          description: Identificativo univoco definito dalla Comunità Europea del procedimento amministrativo  
          example: P17.1    
        name:
          type: string
          description: Nome del procedimento amministrativo  
          example: Anagrafica Light
        description:
          type: string
          description: Descrizione del procedimento amministrativo
          example: Secondo questa procedura, le autorità competenti (regimi pensionistici e assicurativi obbligatori) sono tenute ad accettare la domanda di registrazione di un datore di lavoro per via elettronica.”
        publicOrganization:
          $ref: '#/components/schemas/publicOrganization'

    publicOrganization:
      type: object
      description: Identificativo univoco definito dall’Comunità Europea
      required:
        - publicOrganizationId
        - preferredLabel
        - locationGeographicId
      properties:
        publicOrganizationId:
          type: string
          description: Identificativo della Pubblica Amministrazione di appartenenza 
          example: P06
        preferredLabel:
          type: string
          description: Etichetta preferita per l’identificazione della Pubblica Amministrazione di appartenenza
          example: inail
        locationGeographicId:
          type: string
          description: Identificativo per la Locazione geografica della Pubblica Amministrazione di appartenenza   
          example: GI6


    Errore:
      type: object
      properties:
        publicServiceListResponse:

          required:
            - code
            - message
          type: object
          properties:
            code:
              type: string
              description: Codice di errore
              example: <HTTP_CODE>
              enum:
                - '400'
                - '401'
                - '402'
                - '403'
                - '404'
                - '429'
                - '^5\d{2}$'
            message:
              type: string
              description: Tipologia di errore
              example: <HTTP_STATUS>
              enum:
                - Bad Request
                - Unauthorized
                - No Rows Selected
                - Forbidden 
                - Not Found 
                - Too Many Requests 
                - Internal Server Error
            description:
              type: string
              description: Descrizione di dettaglio dello specifico problema verificatosi
              example: <detail_error>
          description: Modello di risposta in caso di errore 
          
  securitySchemes:
    Authorization:            # Bearer <Voucher PDND>
      type: http
      scheme: bearer
      bearerFormat: JWT       
    