#UNHAPPY PATH: retrieveDataServiceList  - 400 # status code
openapi: 3.0.0
info:
  title: lista dal Data Service l’identificativo della Tipologia di Prova e le informazioni descrittive 
  description: Recupera dal Data Service Directory l’identificativo e le informazioni descrittive dell’Ente Erogatore
  version: 1.0.3
servers:
  - url: http://<url_service_catalog>
    description: Local server
  - url: http://<url_service_catalog>
    description: Development server
  - url: http://<url_service_catalog>
    description: Test server
  - url: http://<url_service_catalog>
    description: Certification server
  - url: http://<url_service_catalog>
    description: Production server
paths:
  /api/v1/data-service/list/:
    get:
      security:
        - Authorization: []         
      tags:
        - retrieveDataServiceList 
      summary: restituisce l’identificativo e le informazioni descrittive dell’Ente Erogatore  
      description: il metodo get restituisce l’identificativo e le informazioni descrittive dell’Ente Erogatore
      parameters:
        - in: query
          name: queryId
          required: true
          schema:
            type: string
          description: Questo parametro deve essere valorizzato con la seguente stringa "urn:oots:dsd:ebxmlregrep:queries:dataservices-by-evidencetypeand-jurisdiction" 
        - in: query
          name: evidenceType
          required: true
          schema:
            type: string
          description: Identificativo del tipo di prova
        - in: query
          name: countryCode
          required: true
          schema:
            type: string
          description: 2 lettere ISO 3166-1 alpha-2 del prefisso internazionale.       
        - in: query
          name: adminUnitL2
          required: false
          schema:
            type: string
          description: 2 Codice NUTS da 3 a 6 lettere.         
        - in: query
          name: adminUnitL3
          required: false
          schema:
            type: string
          description: Codice LAU
        - in: query
          name: userIdentificationOrigin
          required: true
          schema:
            type: string
          description: Locazione utente dello schema eID usato per l’autenticazione.DEVE essere un codice paese di due lettere di ISO 3166-1 alpha-2.         
      responses:
        '400':    # status code
          description: Bad Request
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/QueryResponse'
components:
  schemas:
  
    Slot:
      type: object
      xml:
        prefix: 'rim'
      required:
        - SlotValue
      properties:
        name:
          type: string
          example: JurisdictionDetermination 
          enum:
           - JurisdictionDetermination
           - UserRequestedClassificationConcepts
          xml:
            attribute: true
        SlotValue:
          type: object
          xml:
            prefix: 'rim'
          required:
            - xsi:type
          properties:
            xsi:type:
              type: string
              example: rim:AnyValueType
              xml:
                attribute: true      
            sdg:EvidenceProviderJurisdictionDetermination:
              type: object
              properties:
                sdg:JurisdictionContextId:
                  type: string
                  description: response della Data Service Directory all’utente
                sdg:JurisdictionContext:
                  type: string
                  description: Il contesto della giurisdizione stessa. Nella lingu visualizzare nell’interfaccia utente del richiedente di prove
                sdg:JurisdictionLevel:
                  type: string
                  description: Il livello di giurisdizione richiesto, definend granularita' richiesta della giurisdizione

            sdg:EvidenceProviderClassification:
              type: object
              properties:
                sdg:ClassificationConcept:
                  type: object
                  properties:
                    sdg:Identifier:
                      type: string
                      example: TypeOfInsurance 
                      description: Identificatore del filtro
                    sdg:Type:
                      type: string
                      example: String
                      description: Tipo di dato
                    sdg:ValueExpression:
                      type: string
                      example: ^\d{5}$
                      description: Sintassi filtro attraverso Espressione Regolare  
                    sdg:Description:
                      type: object
                      description: Descrizione del filtro. esempio, Type of insurance
                      properties:
                        lang:
                          type: string
                          example: en
                          xml:
                            attribute: true 
                          description: Specifica il linguaggio       
  
    QueryResponse:
      required:
       - status
       - Exception
      type: object
      xml:
        prefix: 'query'
        namespace: urn:oasis:names:tc:ebxml-regrep:xsd:query:4.0
      properties:
        xmlns:
          type: string
          default: urn:oasis:names:tc:ebxml-regrep:xsd:lcm:4.0
          xml:
            attribute: true
        xmlns:lcm:
          type: string
          default: urn:oasis:names:tc:ebxml-regrep:xsd:lcm:4.0
          xml:
            attribute: true
        xmlns:rim:
          type: string
          default: urn:oasis:names:tc:ebxml-regrep:xsd:rim:4.0
          xml:
            attribute: true
        xmlns:rs:
          type: string
          default: urn:oasis:names:tc:ebxml-regrep:xsd:rs:4.0
          xml:
            attribute: true    
        xmlns:xsi:
          type: string
          default: http://www.w3.org/2001/XMLSchema-instance
          xml:
            attribute: true      
        xsi:schemaLocation:
          type: string
          default: urn:oasis:names:tc:ebxml-regrep:xsd:lcm:4.0
          xml:
            attribute: true  
        status:
          type: string
          default: urn:oasis:names:tc:ebxml-regrep:ResponseStatusType:Failure
          xml:
            attribute: true
        Exception:
          required:
           - xsi:type
           - severity
           - message
          type: object
          xml: 
            prefix: 'rs'
          properties:
            xsi:type:
              type: string
              default: rs:ObjectNotFoundExceptionType

              xml:
                attribute: true
            severity:
              type: string
              default: urn:oasis:names:tc:ebxml-regrep:ErrorSeverityType:Error
              xml:
                attribute: true            
            message:
              type: string
              default: The requirement requested, represented by the requirement id, does not exist
              xml:
                attribute: true                 
            detail:
              type: string
              description: Deve contenere informazioni dettagliate sull'errore, ad esempio informazioni tecniche o una traccia dello stack.
              xml:
                attribute: true
            code:
              type: string
              default: EB:ERR:0002
              xml:
                attribute: true  
            Slot:
              type: array
              items:
                $ref: '#/components/schemas/Slot'
              example:
               - name: JurisdictionDetermination
                 SlotValue:
                   xsi:type: rim:AnyValueType
                   sdg:EvidenceProviderJurisdictionDetermination:
                     sdg:JurisdictionContextId:
                     sdg:JurisdictionContext:
                     sdg:JurisdictionLevel:
               - name: UserRequestedClassificationConcepts
                 SlotValue:
                   xsi:type: rim:AnyValueType
                   sdg:EvidenceProviderClassification:
                     sdg:ClassificationConcept:
                       sdg:Identifier:
                       sdg:Type:
                       sdg:ValueExpression:
                       sdg:Description:
                         lang: en


  securitySchemes:
    Authorization:            # Bearer <Voucher PDND>
      type: http
      scheme: bearer
      bearerFormat: JWT     